### ISSUE TITLE
MINOR: laminext.dev page crashes when cookies are disabled on chrome

### ISSUE THREAD

**Issue by pbuszka** [tulz-app/laminext#52]
A minor thing: I have disabled cookies in my browser and seems that it is not well handled by the doc site
BTW laminext is a nice piece of code :)

```
main.bundle.544cbe62fcbff49ca9c0.js:1 ObserverError: SecurityError: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
fP.r.Nl(https://laminext.dev/main.bundle.544cbe62fcbff49ca9c0.js:1:591917)
mD(https://laminext.dev/main.bundle.544cbe62fcbff49ca9c0.js:1:585412)
new fP(https://laminext.dev/main.bundle.544cbe62fcbff49ca9c0.js:1:856392)
tI.r.La(https://laminext.dev/main.bundle.544cbe62fcbff49ca9c0.js:1:710328)
GG(https://laminext.dev/main.bundle.544cbe62fcbff49ca9c0.js:1:895288)
{anonymous}()(https://laminext.dev/main.bundle.544cbe62fcbff49ca9c0.js:1:950866)
e_.i(https://laminext.dev/main.bundle.544cbe62fcbff49ca9c0.js:1:696695)
Ln(https://laminext.dev/main.bundle.544cbe62fcbff49ca9c0.js:1:86523)
{anonymous}()(https://laminext.dev/main.bundle.544cbe62fcbff49ca9c0.js:1:86269)
new _n(https://laminext.dev/main.bundle.544cbe62fcbff49ca9c0.js:1:86321)
(anonymous) @ main.bundle.544cbe62fcbff49ca9c0.js:1
index.js:1 Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at https://stats.laminext.dev/js/index.js:1:160
    at https://stats.laminext.dev/js/index.js:1:1348
    ```

**Comment by yurique** [comment]
Oh, interesting. So disabling cookies disabled the local storage as well. Which is used to store the state of the checkboxes. Which are implemented using one of the utilities (`storedBoolean`).

This makes it a bug :). I'll get it fixed a bit later today. Thanks for bringing this up!

**Comment by yurique** [comment]
@pbuszka this should be fixed in `v0.13.8`. I think I managed to reproduce it and confirm it's fixed, could you also verify?

**Comment by pbuszka** [comment]
Sorry for later reponse, missed your message. Looks alright on my system now.

**Comment by yurique** [comment]
Great!
